LYS_schoolapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from students import urls as students_urls
from report import urls as report_urls
from account import urls as account_urls
from django.contrib.auth import views as auth_views

from django.views.generic.base import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='students/')),  # Redirect to students app
    path('admin/', admin.site.urls),
    path('students/', include(students_urls)),
    path('report/', include(report_urls)),
    path('', include(account_urls)),
    path('logout/', auth_views.LogoutView.as_view(template_name='account/logout.html'), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib import admin

app_name = 'account'

urlpatterns = [
    # path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('signup/', views.signup, name='signup'),
    # path('login/', LoginView.as_view(template_name='account/login.html'), name='login'),
    path('login/', views.login_view, name='login'),
    # path('logout/', LogoutView.as_view(next_page='account:home'), name='logout'),
    path('change_password/', views.change_password, name='change_password'),
    path('password_change_done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('view_profile/', views.view_profile, name='view_profile'),
    # path('admin/logout/', views.custom_logout, name='admin_logout'),  # Custom logout URL for admin
    # path('logout/', views.custom_logout, name='logout'),  # Custom logout URL for frontend user
    # path('admin_logout/', views.admin_logout, name='admin_logout'),
]

report/urls.py
from django.urls import path
from . import views
from .views import daily_report_view, monthly_report_view

app_name = 'report'
urlpatterns = [
    path('daily-report/', daily_report_view, name='daily_report'),
    path('monthly-report/', monthly_report_view, name='monthly_report'),
    path('installments-unpaid/', views.installments_unpaid_report, name='installments_unpaid_report'),
    path('expenses/', views.expenses_report, name='expenses_report'),
]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'
urlpatterns = [
    path('accounts_home/', views.accounts_home, name='accounts_home'),
    path('student_affairs_home/', views.student_affairs_home, name='student_affairs_home'),
    path('administration_home/', views.administration_home, name='administration_home'),
    path('', views.home, name='home'),
    path('students/', views.student_list, name='student_list'),
    path('student_detail/<int:pk>/', views.student_detail, name='student_detail'),
    path('delete_installment/<int:pk>/', views.delete_installment, name='delete_installment'),
    path('edit_student/<int:pk>/', views.edit_student, name='edit_student'),
    # path('register/', views.register, name='register'),
    path('add_student/', views.add_student, name='add_student'),
    path('delete_student/<int:student_id>/', views.delete_student, name='delete_student'),
    path('students/confirm_delete_student/<int:student_id>/', views.confirm_delete_student, name='confirm_delete_student'),
    path('add_expense/<int:pk>/', views.add_expense, name='add_expense'),
    path('pay_installment/<int:pk>/', views.pay_installment, name='pay_installment'),
    path('receipt/<int:pk>/', views.receipt, name='receipt'),
    path('report/', views.report, name='report'),
    path('daily_report/', views.generate_daily_report, name='daily_report'),
    path('all_reports/', views.all_reports, name='all_reports'),
    path('classroom/<int:classroom_id>/', views.classroom_details, name='classroom_details'),
    path('search/', views.search_student, name='search_student'),
    path('generate-student-report/', views.generate_student_report, name='generate_student_report'),
    path('generate-installment-report/', views.generate_installment_report, name='generate_installment_report'),
    path('g-reports/', views.g_reports, name='g_reports'),
    path('upgrade-students/', views.upgrade_students_view, name='upgrade_students'),
    path('dashboard/', views.student_dashboard, name='student_dashboard'),
    path('export/', views.export_students, name='export_students'),
]

students/views.py
import decimal
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import *
from .forms import *
from django.core.paginator import Paginator
from django.views.decorators.cache import never_cache
from django.db.models import Q
from datetime import date
from django.db.models import Sum, F, ExpressionWrapper, DecimalField, Case, When, F, IntegerField
from datetime import timedelta
from decimal import Decimal
from reportlab.pdfgen import canvas
from django.http import HttpResponse
from tablib import Dataset
from .resources import StudentResource

# Create your views here.
@never_cache
@login_required
def home(request):
    user = request.user
    if user.department == 'accounts':
        return redirect('accounts_home')
    elif user.department == 'student_affairs':
        return redirect('student_affairs_home')
    elif user.department == 'administration':
        return redirect('administration_home')
    else:
        students = Student.objects.all()
        paginator = Paginator(students, 10)  # Display 10 students per page
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'students': page_obj,
            'page_obj': page_obj,  # Pass the page_obj variable to the template 
        }
        return render(request, 'students/home.html', context)

@never_cache
@login_required
def accounts_home(request):
    
    return render (request, 'students/accounts_home.html')


@never_cache
@login_required
def student_affairs_home(request):
    return render(request, 'students/student_affairs_home.html')


@never_cache
@login_required    
def administration_home(request):
    context = {
        
    }
    return render (request, 'students/administration_home.html', context)


@never_cache
@login_required
def add_student(request):
    if request.method == 'POST':
        student_form = StudentForm(request.POST)
        if student_form.is_valid():
            student = student_form.save(commit=False)  # Save the student object without committing to the database
            # Perform any necessary modifications to the student object here
            student.save()  # Save the student object to generate an ID
            student_form.save_m2m()  # Save the many-to-many relationships after saving the student
            messages.success(request, 'Student added successfully!')
            return redirect('students:student_list') # student_list or  add_student
    else:
        student_form = StudentForm()
   
    context = {
        'student_form': student_form,
    }
    return render(request, 'students/add_student.html', context)
# from django.db import transaction

# def add_student(request):
#     if request.method == 'POST':
#         student_form = StudentForm(request.POST)
#         if student_form.is_valid():
#             with transaction.atomic():
#                 student = student_form.save()
#                 student_form.save_m2m()
#             messages.success(request, 'Student information updated successfully!')
#             return redirect('students:student_list')
#     else:
#         student_form = StudentForm()
        
#     context = {
#         'student_form': student_form,
#     }
#     return render(request, 'students/add_student.html', context)


@never_cache
@login_required
def search_student(request):
    query = request.GET.get('query')
    students = Student.objects.all().order_by('name')

    if query and query.strip():
        students = students.filter(Q(name__icontains=query) | Q(national_number__icontains=query))

    paginator = Paginator(students, 5)  # Display 5 students per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'students': page_obj,
        'query': query,
        'page_obj': page_obj,
    }
    return render(request, 'students/search_student.html', context)



@never_cache
@login_required
def student_list(request):
    # Retrieve all students
    students = Student.objects.all()

    # Create an instance of the search form
    search_form = StudentSearchForm(request.GET)

    # Apply search filter if provided
    if search_form.is_valid():
        search_query = search_form.cleaned_data.get('search_query')
        educational_stage = search_form.cleaned_data.get('educational_stage')
        gender = search_form.cleaned_data.get('gender')
        date_of_birth = search_form.cleaned_data.get('date_of_birth')
        classroom = search_form.cleaned_data.get('classroom')

        if search_query:
            students = students.filter(
                Q(name__icontains=search_query) | Q(national_number__icontains=search_query)
            )
        if educational_stage:
            students = students.filter(classroom__educational_stage=educational_stage)
        if gender:
            students = students.filter(gender=gender)
        if date_of_birth:
            students = students.filter(date_of_birth=date_of_birth)
        if classroom:
            students = students.filter(classroom=classroom)

    # Paginate the student list
    paginator = Paginator(students, 10)  # Show 10 students per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    # Total male students
    total_male_students = students.filter(gender='M').count()

    # Total female students
    total_female_students = students.filter(gender='F').count()

    context = {
        'total_male_students': total_male_students,
        'total_female_students': total_female_students,
        'students': students,
        'page_obj': page_obj,
        'search_form': search_form,
    }
    return render(request, 'students/student_list.html', context)

@never_cache
@login_required
def edit_student(request, pk):
    student = get_object_or_404(Student, pk=pk)
    if request.method == 'POST':
        form = Student_edit_Form(request.POST, instance=student)
        if form.is_valid():
            form.save()
            messages.success(request, 'Student information updated successfully!')
            return redirect('students:student_list')
    else:
        form = Student_edit_Form(instance=student)
        # print(form.errors)
        
    context = {
        'form': form,
        'title': 'Edit Student',
    }
    return render(request, 'students/edit_student_form.html', context)

@never_cache
@login_required
def delete_student(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    if request.method == 'POST':
        student.delete()
        messages.success(request, 'Student deleted successfully!')
        return redirect('students:home')
    context = {
        'student': student,
    }
    return render(request, 'students/delete_student.html', context)

@never_cache
@login_required
def confirm_delete_student(request, student_id):
    student = get_object_or_404(Student, id=student_id)
    if request.method == 'POST':
        student.delete()
        messages.success(request, 'Student deleted successfully!')
        return redirect('students:home')
    context = {
        'student': student,
    }
    return render(request, 'students/confirm_delete_student.html', context)

@never_cache
@login_required
def add_expense(request, classroom_id):
    classroom = get_object_or_404(Classroom, id=classroom_id)
    students = classroom.students.all()

    if request.method == 'POST':
        expense_type = request.POST['expense_type']
        amount = request.POST['amount']
        date = request.POST['date']

        for student in students:
            Expense.objects.create(student=student, classroom=classroom, expense_type=expense_type, amount=amount, date=date)

        messages.success(request, 'Expenses added successfully!')
        return redirect('add_expense', classroom_id=classroom_id)

    context = {
        'classroom': classroom,
    }

    return render(request, 'students/add_expense.html', context)



@never_cache
@login_required
def pay_installment(request, pk):
    user = request.user
    student = get_object_or_404(Student, pk=pk)
    
    student_name = student.name
    national_number = student.national_number

    if request.method == 'POST':
        installment_form = TuitionForm(request.POST)
        if installment_form.is_valid():
            installment = installment_form.save(commit=False)
            installment.student = student
            installment.user = user  # Set the user attribute to the current user who is logged in
            installment.paid = True
            installment.save()
            messages.success(request, 'Installment paid successfully!')
            return redirect('students:student_detail', pk=pk)
    else:
        installment_form = TuitionForm()

    context = {
        'student': student,
        'student_name': student_name,
        'national_number': national_number,
        'installment_form': installment_form,
    }
    return render(request, 'students/pay_installment.html', context)

@never_cache
@login_required
def add_comment(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('comments:list')
    else:
        form = CommentForm()
    
    return render(request, 'add_comment.html', {'form': form})

def comment_list(request):
    comments = Comment.objects.all()
    return render(request, 'comment_list.html', {'comments': comments})


@never_cache
@login_required
def receipt(request, pk):
    tuition = get_object_or_404(Tuition, pk=pk)
    student = tuition.student
    installments = Tuition.objects.filter(student=student)
    total_paid = sum(installment.amount_tuition for installment in installments if installment.paid)
    classroom = student.classroom.first()

students/templates/students/base/administration_navbar.html
{% load static %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.rtl.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">

<!-- Bootstrap Grid -->
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.rtl.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.rtl.min.css' %}">

<!-- Bootstrap Reboot -->
<link rel="stylesheet" href="{% static 'css/bootstrap-reboot.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-reboot.rtl.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-reboot.rtl.min.css' %}">

<!-- Bootstrap Utilities -->
<link rel="stylesheet" href="{% static 'css/bootstrap-utilities.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-utilities.min.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-utilities.rtl.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap-utilities.rtl.min.css' %}">

<!-- Custom CSS -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<!-- ICON -->
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-DfFM3Lw7K8HYJBm57L/GhGzMOEwZrSvWz+/+Lb/aWb1CtPz4+E5f5cYVtcFMzDfG" crossorigin="anonymous">

<!-- Bootstrap Icons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons%401.5.0/font/bootstrap-icons.css" integrity="sha384-nDw2I+O6iZ3xvQ/7xhPmJNnK5BZ/+VcEeQbK9v+1JqA7n8qJZ9YyGmzQ5RjZw1d" crossorigin="anonymous">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.2/css/bootstrap.min.css" integrity="sha512-xIUVMw9jyfjQy7VJ1amv2B5YbI/5sQ0SbR4oJxU9E7gVh2QOeZ5s7rZiN4Zs3qbjZkSgGf0Lh+RZsA6F/iOqXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<!-- end ICON -->

</head>
<body>
<!-- Navbar -->
  
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'students:administration_home' %}">
        <img src="{% static 'img/logo.png' %}" alt="Logo" width="80">
      </a>
      <a class="navbar-brand" href="{% url 'students:administration_home' %}">Al Manar School Account App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'administration_home' %}active{% endif %}" href="{% url 'students:administration_home' %}">الرئيسية</a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'student_list' %}active{% endif %}" href="{% url 'students:student_list' %}">قائمة الطلاب</a>
          </li> {% endcomment %}
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'all_reports' %}active{% endif %}" href="{% url 'students:all_reports' %}">جميع الاحصائيات</a>
          </li>
           <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'report' %}active{% endif %}" href="{% url 'students:report' %}">Reports</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'daily_report' %}active{% endif %}" href="{% url 'students:daily_report' %}"> تقرير يومي</a>
          </li>
           {% comment %} <li class="nav-item">
            <a class="nav-link" href="{% url 'students:g_reports' %}">Generated Reports</a>
          </li>  {% endcomment %}
        </ul>
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:view_profile' %}">Welcome, {{ user.username }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:change_password' %}">Change Password</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Log out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:signup' %}">Sign up</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="container py-4">
{% block content %}

{% endblock %}
  </div>
{% include 'students/base/footer.html' %}

<!-- Bootstrap JS Bundle -->
<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js.map' %}"></script>

<!-- Bootstrap ES Modules -->
<script src="{% static 'js/bootstrap.esm.js' %}"></script>
<script src="{% static 'js/bootstrap.esm.min.js' %}"></script>
<script src="{% static 'js/bootstrap.esm.min.js.map' %}"></script>

<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js.map' %}"></script>

<!-- Font Awesome -->
<script src="{% static 'js/fontawesome.js' %}"></script>

<!-- Popper.js -->
<script src="{% static 'js/popper.min.js' %}"></script>

<!-- Tether -->
<script src="{% static 'js/tether.min.js' %}"></script>
<!-- Initialize the Bootstrap dropdown component -->
<script>
  $(document).ready(function() {
    $('.dropdown-toggle').dropdown();
  });
  var dropdownElementList = [].slice.call(document.querySelectorAll('.dropdown-toggle'))
  var dropdownList = dropdownElementList.map(function (dropdownToggleEl) {
    return new bootstrap.Dropdown(dropdownToggleEl)
  })
</script>

</body>
</html> 

students/templates/students/base/footer.html
<footer class="bg-light text-center py-3">
    Made by Eng. Muhammad Gamal | © 2023 All Rights Reserved | Al Manar Code Team 
</footer>

students/templates/students/base/nav.html
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="#">Al Manar School Account App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="{% url 'students:home' %}">Home</a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'student_list' %}active{% endif %}" href="{% url 'students:student_list' %}">Students</a>
          </li> {% endcomment %}
          {% comment %} <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'add_student' %}active{% endif %}" href="{% url 'students:add_student' %}">Add Student</a>
          </li> {% endcomment %}
           <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'report' %}active{% endif %}" href="{% url 'students:report' %}">Reports</a>
          </li> 
          {% comment %} <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'search_student' %}active{% endif %}" href="{% url 'students:search_student' %}">Search Students</a>
          </li> {% endcomment %}
           <li class="nav-item">
            <a class="nav-link" href="{% url 'students:g_reports' %}">Generated Reports</a>
          </li> 
        </ul>
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'account:view_profile' %}">Welcome, {{ user.username }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'account:change_password' %}">Change Password</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'account:logout' %}">Log out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'account:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'account:signup' %}">Sign up</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

students/templates/students/base/nav_staff.html
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="#">Al Manar School Account App</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="{% url 'students:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'student_list' %}active{% endif %}" href="{% url 'students:student_list' %}">Students</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'add_student' %}active{% endif %}" href="{% url 'students:add_student' %}">Add Student</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'search_student' %}active{% endif %}" href="{% url 'students:search_student' %}">Search Students</a>
          </li>
          
        </ul>
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'account:view_profile' %}">Welcome, {{ user.username }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'account:change_password' %}">Change Password</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'account:logout' %}">Log out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'account:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'account:signup' %}">Sign up</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <br>